### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by dsaito** [gincoin-dev/gincoin-core#5]
When compiling the wallet on a raspberr pi, I get the following message:

Making all in src
make[1]: Entering directory '/home/pi/gincoin-core/src'
make[2]: Entering directory '/home/pi/gincoin-core/src'
  CXX      crypto/libgincoinconsensus_la-hmac_sha512.lo
  CXX      crypto/libgincoinconsensus_la-ripemd160.lo
  CXX      crypto/libgincoinconsensus_la-sha1.lo
  CXX      crypto/libgincoinconsensus_la-sha256.lo
  CXX      crypto/libgincoinconsensus_la-sha512.lo
  CXX      libgincoinconsensus_la-hash.lo
  CXX      primitives/libgincoinconsensus_la-transaction.lo
  CXX      libgincoinconsensus_la-pubkey.lo
  CXX      script/libgincoinconsensus_la-gincoinconsensus.lo
  CXX      script/libgincoinconsensus_la-interpreter.lo
  CXX      script/libgincoinconsensus_la-script.lo
  CXX      libgincoinconsensus_la-uint256.lo
  CXX      libgincoinconsensus_la-utilstrencodings.lo
make[3]: Entering directory '/home/pi/gincoin-core/src/secp256k1'
I. -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
/bin/bash: I.: command not found
Makefile:1500: recipe for target 'gen_context.o' failed
make[3]: [gen_context.o] Error 127 (ignored)
gen_context.o -o gen_context
/bin/bash: gen_context.o: command not found
Makefile:1503: recipe for target 'gen_context' failed
make[3]: *** [gen_context] Error 127
make[3]: Leaving directory '/home/pi/gincoin-core/src/secp256k1'
Makefile:10038: recipe for target 'secp256k1/libsecp256k1.la' failed
make[2]: *** [secp256k1/libsecp256k1.la] Error 2
make[2]: Leaving directory '/home/pi/gincoin-core/src'
Makefile:9532: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/gincoin-core/src'
Makefile:645: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by juancarlosy182** [comment]
hola pudiste solucionar ? me gustaría poder tenerla tambien en un raspberry para stalkear saludos desde colombia

**Comment by juancarlosy182** [comment]
> Al compilar la billetera en un raspberr pi, recibo el siguiente mensaje:
> 
> Haciendo todo en src 
> make [1]: Ingresando al directorio '/ home / pi / gincoin-core / src' 
> make [2]: Ingresando al directorio '/ home / pi / gincoin-core / src' 
> CXX crypto / libgincoinconsensus_la-hmac_sha512.lo 
> CXX crypto / libgincoinconsensus_la-ripemd160.lo 
> CXX crypto / libgincoinconsensus_la-sha1.lo 
> CXX crypto / libgincoinconsensus_la-sha256.lo 
> CXX crypto / libgincoinconsensus_la-sha512.lo 
> CXX libgincoinconsensus_la-hash.lo 
> primitivas CXX / libgincoinconsensus_la-transaction.lo 
> CXX libgincoinconsensus_la-pubkey .lo 
> script CXX / libgincoinconsensus_la-gincoinconsensus.lo 
> script CXX / libgincoinconsensus_la-interpreter.lo
> CXX script / libgincoinconsensus_la-script.lo 
> CXX libgincoinconsensus_la-uint256.lo 
> CXX libgincoinconsensus_la-utilstrencodings.lo 
> make [3]: Ingresando en el directorio 'home / pi / gincoin-core / src / secp256k1' 
> I. -Wall -Wnotra función no utilizada -c src / gen_context.c -o gen_context.o 
> / bin / bash: I .: comando no encontrado 
> Makefile: 1500: la receta para el objetivo 'gen_context.o' falló 
> make [3]: [gen_context.o] Error 127 (ignorado) 
> gen_context.o -o gen_context 
> / bin / bash: gen_context.o: comando no encontrado 
> Makefile: 1503: la receta para el objetivo 'gen_context' falló 
> make [3]: *** [gen_context] Error 127 
> make [3] : Saliendo del directorio '/ home / pi / gincoin-core / src / secp256k1'
> Makefile: 10038: la receta para el objetivo 'secp256k1 / libsecp256k1.la' falló 
> make [2]: *** [secp256k1 / libsecp256k1.la] Error 2 
> make [2]: Saliendo del directorio '/ home / pi / gincoin-core / src ' 
> Makefile: 9532: la receta para el objetivo' todo-recursivo 'falló 
> make [1]: *** [all-recursive] Error 1 
> make [1]: Saliendo del directorio' / home / pi / gincoin-core / src ' 
> Makefile: 645: 
> error en la receta para el objetivo 'todo recursivo' : *** [todo recursivo] Error 1

amigo espero puedas hecharme una mano te agradeceria mucho si puedes explicarme un par de cosas y aun mas si pudiste compilarlo en raspepberry , jcyepes18@gmail.com es mi correo nuevamente gracias

**Comment by juancarlosy182** [comment]
> When compiling the wallet on a raspberr pi, I get the following message:
> 
> Making all in src
> make[1]: Entering directory '/home/pi/gincoin-core/src'
> make[2]: Entering directory '/home/pi/gincoin-core/src'
> CXX crypto/libgincoinconsensus_la-hmac_sha512.lo
> CXX crypto/libgincoinconsensus_la-ripemd160.lo
> CXX crypto/libgincoinconsensus_la-sha1.lo
> CXX crypto/libgincoinconsensus_la-sha256.lo
> CXX crypto/libgincoinconsensus_la-sha512.lo
> CXX libgincoinconsensus_la-hash.lo
> CXX primitives/libgincoinconsensus_la-transaction.lo
> CXX libgincoinconsensus_la-pubkey.lo
> CXX script/libgincoinconsensus_la-gincoinconsensus.lo
> CXX script/libgincoinconsensus_la-interpreter.lo
> CXX script/libgincoinconsensus_la-script.lo
> CXX libgincoinconsensus_la-uint256.lo
> CXX libgincoinconsensus_la-utilstrencodings.lo
> make[3]: Entering directory '/home/pi/gincoin-core/src/secp256k1'
> I. -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
> /bin/bash: I.: command not found
> Makefile:1500: recipe for target 'gen_context.o' failed
> make[3]: [gen_context.o] Error 127 (ignored)
> gen_context.o -o gen_context
> /bin/bash: gen_context.o: command not found
> Makefile:1503: recipe for target 'gen_context' failed
> make[3]: *** [gen_context] Error 127
> make[3]: Leaving directory '/home/pi/gincoin-core/src/secp256k1'
> Makefile:10038: recipe for target 'secp256k1/libsecp256k1.la' failed
> make[2]: *** [secp256k1/libsecp256k1.la] Error 2
> make[2]: Leaving directory '/home/pi/gincoin-core/src'
> Makefile:9532: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/pi/gincoin-core/src'
> Makefile:645: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1

friend I hope you can give me a hand I would appreciate it if you can explain a couple of things and even more if you could compile it in raspberry, jcyepes18@gmail.com is my mail again thanks

**Comment by gincoin-dev** [comment]
This repo has moved: https://github.com/GIN-coin/gincoin-core

In the new repo you can also find binaries for ARM64 to avoid issues with compiling on R.PI: https://github.com/GIN-coin/gincoin-core/releases/download/v1.1.0.0/gincoin-binaries-arm64.zip

**Comment by juancarlosy182** [comment]
> para

thanks

**Comment by juancarlosy182** [comment]
> This repo has moved: https://github.com/GIN-coin/gincoin-core
> 
> In the new repo you can also find binaries for ARM64 to avoid issues with compiling on R.PI: https://github.com/GIN-coin/gincoin-core/releases/download/v1.1.0.0/gincoin-binaries-arm64.zip

thanks for your help

I am new and I am very interested in your project, you could give me a reference of where and compile for raspberry and a million thanks
